<div style="text-align: center;"><div style="font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);"><span style="font-weight: 700;"><span style="font-size: 28px;">{DELHI PUBLIC SCHOOL KISHANGANJ}</span><span style="font-size: 28px;">&nbsp;</span></span></div>
<div style="font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);">{institute_email} | {mobileno}&nbsp;</div>
<div style="font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);">{institute_address}</div>
<div style="font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);"><br></div>
<div style="font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);"><span style="font-weight: 700;">Registration No</span>: {register_no}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {student_photo}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span style="font-weight: 700;">Admission On</span>: {admission_date}</div>
<div style="font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);"><br></div>
<div style="font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);"><span style="font-size: 24px;"><span style="font-weight: 700;">SCHOOL CERTIFICATE EXAMINATION-2020</span></span></div>
<div style="font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0); line-height: 1.2;"><span style="font-size: 24px;"><span style="font-weight: 700;"><br></span></span><div style="line-height: 1.2;"><font face="Pinyon Script"><span style="font-size: 28px; font-style: italic;">This Is To Certify That&nbsp;&nbsp;{{$firstname}}&nbsp;{{$lastname}}</span></font></div>
<div style="line-height: 1.2;"><font face="Pinyon Script"><span style="font-size: 28px; font-style: italic;"><span style="font-weight: 700;"><br></span>And Of He/she Is Gender As&nbsp;{{$gender}}&nbsp;Son/daughter Of&nbsp;&nbsp;{{$fathername}}</span></font><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;;">&nbsp;</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;;">&nbsp;Of&nbsp;</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;; font-weight: 700;">{institute_name}</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;;">&nbsp;And&nbsp;</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;; font-weight: 700;">{institute_address}</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;;">&nbsp;</span></div>
<div style="line-height: 1.2;"><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;;">Bearing Roll-&nbsp;</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;; font-weight: 700;">{roll}&nbsp;</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;;">&amp; Exam Center Campus-04 And Class&nbsp;</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;; font-weight: 700;">{class}&nbsp;</span><span style="font-size: 28px; font-style: italic; font-family: &quot;Pinyon Script&quot;;">Dulg Passed The Final school Certificate Examination Of 2020.&nbsp;&nbsp;</span></div>
<div style="line-height: 1.2;"><font face="Pinyon Script"><span style="font-size: 28px; font-style: italic;"><span style="font-weight: 700;">{category}</span>&nbsp; And His/her Date Of Birth As Recorded Is&nbsp;<span style="font-weight: 700;">{birthday}</span>&nbsp;Obtained&nbsp; G.p.a&nbsp;<span style="font-weight: 700;">4.94</span>&nbsp;In The Scale Of&nbsp;<span style="font-weight: 700;">5.00</span>.</span></font></div>
<div style="line-height: 1.2;"><font face="Arial" style="font-style: italic;"><br></font></div>
<div style="line-height: 1.2;"><font face="Arial" style="font-style: italic;"><br></font></div>
<div style="line-height: 1.2;"><span style="font-style: italic;"><font face="Arial">Date of Publication of Result: {print_date}&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</font><span style="font-family: Arial;">Principal signature</span></span></div>
<div style="line-height: 1.2;"><span style="font-style: italic;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;{signature}<span style="font-family: Arial;"><br></span></span></div>
<div style="line-height: 1.2;"><font face="Arial" style="font-style: italic;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</font></div>
</div>
</div>